"""Wire vocabulary mirrored from the Swift protocol types.

GENERATED by WorkerProtocolMirrorGenerator. Do not edit.

Regenerate with:
    swift run swift-python-build generate

`SwiftPythonGenTests.testWorkerMirrorMatchesCheckedInFile` fails if this
file differs from fresh output, so a hand edit is caught in CI.
"""

# The worker wire protocol version, from
# `IPCConfiguration.currentProtocolVersion`. This is the only authoring
# site; the guest reports it back through the spawn-time handshake.
CURRENT_PROTOCOL_VERSION = 6

# Every `WorkerCommand` case name. An inbound command outside this
# set is a protocol error, not an unrecognised string.
COMMAND_CASES = frozenset({
    "attachSharedMemory",
    "callbackError",
    "callbackResult",
    "callbackStreamChunk",
    "callbackStreamEnd",
    "callbackStreamError",
    "copyToShared",
    "createSharedBuffer",
    "describeCapabilities",
    "duplexApplicationControl",
    "duplexCancel",
    "duplexClose",
    "duplexInterrupt",
    "duplexOpen",
    "duplexOutputAcknowledged",
    "eval",
    "evalStream",
    "execAuthResponse",
    "execShell",
    "execShellPTY",
    "execShellStream",
    "execSignal",
    "execStdinChunk",
    "getArrayInfo",
    "healthCheck",
    "invoke",
    "invokeResult",
    "invokeStream",
    "method",
    "methodResult",
    "methodStream",
    "registerCallback",
    "release",
    "setResourceLimits",
    "shutdown",
    "store",
    "streamCancel",
    "unregisterCallback",
})

# Every `WorkerResponse` case name.
RESPONSE_CASES = frozenset({
    "arrayInfo",
    "callbackAsyncAck",
    "callbackAsyncInvocation",
    "callbackInvocation",
    "callbackStreamNext",
    "capabilities",
    "copiedToShared",
    "duplexEvent",
    "duplexOpened",
    "duplexTerminal",
    "error",
    "execAuthChallenge",
    "execAuthFailed",
    "execAuthOK",
    "execResult",
    "execStderrChunk",
    "execStdoutChunk",
    "execTimedOut",
    "handle",
    "healthy",
    "notAnArray",
    "payloadTooLarge",
    "pythonError",
    "result",
    "sharedBufferCreated",
    "streamChunk",
    "streamEnd",
    "streamKeepalive",
    "streamProgress",
    "success",
})

# Responses whose channel identifier travels as `streamChannelID`
# instead of `channelID`, from `WorkerResponse.streamChannelKinds`.
STREAM_CHANNEL_RESPONSES = frozenset({
    "streamChunk",
    "streamEnd",
    "streamKeepalive",
    "streamProgress",
})

# Responses whose persistent route is `controlChannelID`, from
# `WorkerResponse.sessionRoutedKinds`.
SESSION_ROUTED_RESPONSES = frozenset({
    "duplexEvent",
    "duplexOpened",
    "duplexTerminal",
})

# Capability names known to this host source.
WORKER_CAPABILITY_NAMES = frozenset({
    "duplex.accelerator.backend.v1",
    "duplex.arena-ingress.v1",
    "duplex.messages.v1",
    "duplex.sessions.v1",
})

# Duplex media transport names known to this host source.
DUPLEX_MEDIA_TRANSPORT_NAMES = frozenset({
    "duplex.arena-reference.v1",
    "duplex.uds.v1",
    "duplex.vsock.v1",
})

# Duplex media authentication modes.
DUPLEX_AUTHENTICATION_MODES = frozenset({
    "hmac-sha256",
})

# Duplex media checksum modes.
DUPLEX_CHECKSUM_MODES = frozenset({
    "crc32c",
    "none",
})

# Runtime-owned duplex event discriminators.
DUPLEX_WORKER_EVENT_CASES = frozenset({
    "application",
    "inputAccepted",
    "inputProcessed",
    "outputProduced",
    "ready",
})

# Duplex terminal discriminators.
DUPLEX_TERMINAL_CASES = frozenset({
    "cancelled",
    "completed",
    "failed",
})

# Namespace keys `eval` scrubs before running new code, from
# `EvalResultSentinel.keys`. Order matters only for readability.
RESULT_SENTINEL_KEYS = (
    "__result__",
    "__swiftpython_return_pickled_result__",
    "__swiftpython_result_object__",
    "__swiftpython_pickled_result__",
)

# Binary sidecar framing: a little-endian u32 entry count, then one
# little-endian u32 length per entry, then the entries back to back.
SIDECAR_LENGTH_STRUCT = "<I"

# Duplex helper/media declarations are linked from Swift. The generated
# `_swiftpython_duplex.py` helper imports these rather than retyping
# them.
DUPLEX_HELPER_SCHEMA_VERSION = 1
DUPLEX_MEDIA_PROTOCOL_VERSION = 1
DUPLEX_MEDIA_MAGIC = 1481655379
DUPLEX_ENVELOPE_FIXED_HEADER_BYTES = 24
DUPLEX_DATA_ENVELOPE_FIXED_BYTES = 40
DUPLEX_MAXIMUM_HANDSHAKE_BYTES = 4096
DUPLEX_SUPPORTED_OPTIONAL_FLAG_MASK = 3
DUPLEX_SUPPORTED_REQUIRED_FLAG_MASK = 0
DUPLEX_MAXIMUM_CONTROL_PAYLOAD_BYTES = 1048576
DUPLEX_MAXIMUM_MEDIA_FRAME_BYTES = 16777216
DUPLEX_MAXIMUM_VSOCK_MEDIA_FRAME_BYTES = 4194304
DUPLEX_MAXIMUM_LOGICAL_MESSAGE_BYTES = 268435456
DUPLEX_PREFERRED_MESSAGE_CHUNK_BYTES = 262144
DUPLEX_MAXIMUM_OUTSTANDING_MESSAGES = 16
DUPLEX_MAXIMUM_ACTIVE_SESSIONS = 16
DUPLEX_MAXIMUM_CREDIT_FRAMES = 4096
DUPLEX_MAXIMUM_PYTHON_CONTROL_EVENTS = 64
DUPLEX_MAXIMUM_PYTHON_INTERRUPTION_EVENTS = 8
DUPLEX_MAXIMUM_FORMATS = 64
DUPLEX_MAXIMUM_FORMAT_METADATA_ENTRIES = 64
DUPLEX_MAXIMUM_DESCRIPTOR_STRING_BYTES = 512
DUPLEX_MAXIMUM_ACCELERATOR_QUEUED_STEPS = 4096
DUPLEX_MAXIMUM_ACCELERATOR_RESIDENT_MODELS = 1024
DUPLEX_MAXIMUM_ACCELERATOR_RESIDENT_BYTES = 68719476736
DUPLEX_MAXIMUM_ACCELERATOR_LEASES = 4096
DUPLEX_MAXIMUM_ACCELERATOR_STATE_ITEMS = 65536
DUPLEX_MAXIMUM_ACCELERATOR_STATE_BYTES = 1073741824
DUPLEX_MAXIMUM_ACCELERATOR_SCHEDULING_WEIGHT = 4096
DUPLEX_MAXIMUM_ACCELERATOR_PROCESS_LANES = 64
DUPLEX_MAXIMUM_INGRESS_CREDIT_BYTES = 67108864
DUPLEX_MAXIMUM_EGRESS_CREDIT_BYTES = 67108864

DUPLEX_MEDIA_ENVELOPE_KINDS = {
    "arenaReference": 9,
    "arenaRelease": 10,
    "credit": 2,
    "data": 1,
    "directionEnd": 3,
    "discontinuity": 4,
    "messageAbort": 8,
    "messageChunk": 7,
    "ping": 5,
    "pong": 6,
}

DUPLEX_MEDIA_DIRECTIONS = {
    "egress": 2,
    "ingress": 1,
}

DUPLEX_MEDIA_ROLES = {
    "host": 1,
    "worker": 2,
}
