"""Generated SwiftPython synchronous duplex-session helper.

GENERATED by WorkerProtocolMirrorGenerator. Do not edit.

Wire constants come from linked Swift declarations through
`_swiftpython_wire.py`. Native functions are injected by the worker;
this module owns the stable Python-facing event and session classes.
"""

import collections
import math
import re
import threading
import time
from enum import Enum

try:
    import _swiftpython_duplex_native as _native
except ModuleNotFoundError as error:
    # The pure-Python VM worker imports this generated module only to
    # produce its honest unavailable-capability declaration. Its
    # artifact deliberately has no process-worker native extension.
    # Do not hide a missing transitive dependency from a real native
    # module, though.
    if error.name != "_swiftpython_duplex_native":
        raise
    _native = None
from _swiftpython_wire import (
    DUPLEX_AUTHENTICATION_MODES,
    DUPLEX_CHECKSUM_MODES,
    DUPLEX_DATA_ENVELOPE_FIXED_BYTES,
    DUPLEX_ENVELOPE_FIXED_HEADER_BYTES,
    DUPLEX_HELPER_SCHEMA_VERSION,
    DUPLEX_MAXIMUM_ACTIVE_SESSIONS,
    DUPLEX_MAXIMUM_CREDIT_FRAMES,
    DUPLEX_MAXIMUM_CONTROL_PAYLOAD_BYTES,
    DUPLEX_MAXIMUM_EGRESS_CREDIT_BYTES,
    DUPLEX_MAXIMUM_HANDSHAKE_BYTES,
    DUPLEX_MAXIMUM_INGRESS_CREDIT_BYTES,
    DUPLEX_MAXIMUM_MEDIA_FRAME_BYTES,
    DUPLEX_MAXIMUM_VSOCK_MEDIA_FRAME_BYTES,
    DUPLEX_MAXIMUM_LOGICAL_MESSAGE_BYTES,
    DUPLEX_PREFERRED_MESSAGE_CHUNK_BYTES,
    DUPLEX_MAXIMUM_OUTSTANDING_MESSAGES,
    DUPLEX_MEDIA_DIRECTIONS,
    DUPLEX_MEDIA_ENVELOPE_KINDS,
    DUPLEX_MEDIA_MAGIC,
    DUPLEX_MEDIA_PROTOCOL_VERSION,
    DUPLEX_MEDIA_ROLES,
    DUPLEX_MEDIA_TRANSPORT_NAMES,
    DUPLEX_SUPPORTED_OPTIONAL_FLAG_MASK,
    DUPLEX_SUPPORTED_REQUIRED_FLAG_MASK,
    DUPLEX_TERMINAL_CASES,
    DUPLEX_WORKER_EVENT_CASES,
    WORKER_CAPABILITY_NAMES,
)


class DuplexCancelledError(RuntimeError):
    """Raised by cooperative session cancellation safe points."""

    def __init__(self, reason):
        self.reason = str(reason)
        super().__init__(f"duplex session cancelled: {self.reason}")


class DuplexMessageAbortedError(RuntimeError):
    """Raised when the sender explicitly aborts an incomplete message."""

    def __init__(self, message_id, reason_code):
        self.message_id = str(message_id)
        self.reason_code = int(reason_code)
        super().__init__(
            f"duplex message {self.message_id} aborted: {self.reason_code}"
        )


class SendDisposition(Enum):
    SENT = "sent"
    WOULD_BLOCK = "would_block"


class InterruptionDisposition(Enum):
    TRUNCATED = "truncated"
    GENERATION_STOPPED_BUT_STATE_NOT_TRUNCATED = (
        "generation_stopped_but_state_not_truncated"
    )
    ALREADY_FINISHED = "already_finished"
    UNSUPPORTED = "unsupported"


class AcceleratorUnavailableError(RuntimeError):
    pass


_MAXIMUM_WARMUP_SHAPES = 256
_MAXIMUM_PHASE_TIMINGS = 256


class BoundedStateWindow:
    """Adapter-owned model state bound, separate from media credit."""

    __slots__ = (
        "_maximum_items",
        "_maximum_bytes",
        "_items",
        "_bytes",
        "_high_water_items",
        "_high_water_bytes",
    )

    def __init__(self, maximum_items, maximum_bytes):
        self._maximum_items = int(maximum_items)
        self._maximum_bytes = int(maximum_bytes)
        if self._maximum_items <= 0 or self._maximum_bytes <= 0:
            raise ValueError("state window bounds must be positive")
        self._items = collections.deque()
        self._bytes = 0
        self._high_water_items = 0
        self._high_water_bytes = 0

    def append(self, value, *, bytes):
        byte_count = int(bytes)
        if byte_count < 0 or byte_count > self._maximum_bytes:
            raise ValueError("state item exceeds bounded window")
        self._items.append((value, byte_count))
        self._bytes += byte_count
        while (
            len(self._items) > self._maximum_items
            or self._bytes > self._maximum_bytes
        ):
            _, removed = self._items.popleft()
            self._bytes -= removed
        self._high_water_items = max(
            self._high_water_items,
            len(self._items),
        )
        self._high_water_bytes = max(
            self._high_water_bytes,
            self._bytes,
        )

    def __len__(self):
        return len(self._items)

    def __iter__(self):
        return (value for value, _ in tuple(self._items))

    @property
    def snapshot(self):
        return {
            "items": len(self._items),
            "bytes": self._bytes,
            "maximum_items": self._maximum_items,
            "maximum_bytes": self._maximum_bytes,
            "high_water_items": self._high_water_items,
            "high_water_bytes": self._high_water_bytes,
        }


_MODEL_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$")


class _ModelEntry:
    __slots__ = (
        "key",
        "model",
        "estimated_bytes",
        "observed_bytes",
        "unload",
        "leases",
        "last_used",
        "ttl_seconds",
        "partition",
    )

    def __init__(
        self,
        key,
        model,
        estimated_bytes,
        observed_bytes,
        unload,
        ttl_seconds,
        partition,
    ):
        self.key = key
        self.model = model
        self.estimated_bytes = int(estimated_bytes)
        self.observed_bytes = int(observed_bytes)
        self.unload = unload
        self.leases = 1
        self.last_used = time.monotonic()
        self.ttl_seconds = float(ttl_seconds)
        self.partition = partition


class _ModelLease:
    __slots__ = ("_registry", "_entry", "_released")

    def __init__(self, registry, entry):
        self._registry = registry
        self._entry = entry
        self._released = False

    def __enter__(self):
        return self._entry.model

    def __exit__(self, exc_type, exc, traceback):
        self.release()
        return False

    def release(self):
        if not self._released:
            self._released = True
            self._registry.release(self._entry.key)

    def __del__(self):
        try:
            self.release()
        except BaseException:
            # Interpreter teardown must not resurrect or report a
            # best-effort lease finalizer.
            pass


class _ModelRegistry:
    """Process-wide single-flight leased TTL/LRU residency registry."""

    def __init__(self):
        self._condition = threading.Condition()
        self._entries = {}
        self._loading = set()
        self._evicting = set()
        self._active_leases = 0
        self._last_cache_clear = 0.0
        self._cache_clear_in_flight = False
        self._last_pressure_action = None
        self._load_count = 0
        self._eviction_count = 0
        self._overage_count = 0

    def _validate_key(self, key):
        if not isinstance(key, str) or _MODEL_KEY.fullmatch(key) is None:
            raise ValueError(
                "model key must be an explicit bounded identifier"
            )
        lowered = key.lower()
        if any(
            marker in lowered
            for marker in ("password", "secret", "bearer", "api_key")
        ):
            raise ValueError("model key must not contain secrets")
        return key

    def _validate_partition(self, partition):
        if partition is None:
            return None
        return self._validate_key(partition)

    def _resident_bytes_locked(self):
        return sum(
            entry.observed_bytes for entry in self._entries.values()
        )

    def _idle_candidates_locked(self, now, force):
        candidates = [
            entry
            for entry in self._entries.values()
            if entry.leases == 0
            and (
                force
                or now - entry.last_used >= entry.ttl_seconds
            )
        ]
        return sorted(candidates, key=lambda entry: entry.last_used)

    def _remove_idle_locked(
        self,
        *,
        accelerator,
        maximum_models,
        maximum_bytes,
        additional_models,
        additional_bytes,
        force_expired,
    ):
        now = time.monotonic()
        removed = []
        candidates = self._idle_candidates_locked(
            now,
            force_expired,
        )
        while (
            len(self._entries) + additional_models > maximum_models
            or self._resident_bytes_locked() + additional_bytes
                > maximum_bytes
        ):
            if not candidates:
                break
            entry = candidates.pop(0)
            if self._entries.pop(entry.key, None) is entry:
                removed.append(entry)
                self._evicting.add(entry.key)
                self._eviction_count += 1
        return removed

    def _unload_entries(self, accelerator, entries):
        first_error = None
        try:
            for entry in entries:
                if entry.unload is not None:
                    try:
                        accelerator.run_step(
                            lambda entry=entry: entry.unload(
                                entry.model
                            ),
                            phase="residency.unload",
                        )
                    except BaseException as error:
                        if first_error is None:
                            first_error = error
        finally:
            with self._condition:
                for entry in entries:
                    self._evicting.discard(entry.key)
                self._condition.notify_all()
        if first_error is not None:
            raise first_error

    def lease(
        self,
        accelerator,
        *,
        key,
        estimated_bytes,
        load,
        unload=None,
        ttl_seconds=None,
        observe_bytes=None,
        partition=None,
    ):
        key = self._validate_key(key)
        partition = self._validate_partition(partition)
        registry_key = (partition, key)
        estimated = int(estimated_bytes)
        if estimated <= 0:
            raise ValueError("estimated_bytes must be positive")
        config = accelerator.configuration
        maximum_models = int(config["maximum_resident_models"])
        maximum_bytes = int(config["maximum_resident_bytes"])
        maximum_leases = int(config["maximum_simultaneous_leases"])
        ttl = (
            float(ttl_seconds)
            if ttl_seconds is not None
            else int(config["default_model_ttl_ms"]) / 1000.0
        )
        if not math.isfinite(ttl) or ttl <= 0:
            raise ValueError("model TTL must be finite and positive")

        while True:
            removed = []
            with self._condition:
                if self._cache_clear_in_flight:
                    raise RuntimeError(
                        "model lease admission is paused during "
                        "cache maintenance"
                    )
                while registry_key in self._loading:
                    self._condition.wait()
                    if self._cache_clear_in_flight:
                        raise RuntimeError(
                            "model lease admission is paused during "
                            "cache maintenance"
                        )
                if registry_key in self._evicting:
                    raise RuntimeError(
                        "model key is being evicted; retry the lease"
                    )
                entry = self._entries.get(registry_key)
                if entry is not None:
                    if entry.observed_bytes > maximum_bytes:
                        raise RuntimeError(
                            "resident model exceeds this lane policy"
                        )
                    if self._active_leases >= maximum_leases:
                        raise RuntimeError(
                            "model lease admission exhausted"
                        )
                    entry.leases += 1
                    entry.last_used = time.monotonic()
                    self._active_leases += 1
                    return _ModelLease(self, entry)
                removed = self._remove_idle_locked(
                    accelerator=accelerator,
                    maximum_models=maximum_models,
                    maximum_bytes=maximum_bytes,
                    additional_models=1,
                    additional_bytes=estimated,
                    force_expired=True,
                )
                if (
                    len(self._entries) + 1 > maximum_models
                    or self._resident_bytes_locked() + estimated
                        > maximum_bytes
                    or self._active_leases >= maximum_leases
                ):
                    raise RuntimeError(
                        "model residency admission exhausted"
                    )
                self._loading.add(registry_key)
            try:
                self._unload_entries(accelerator, removed)
            except BaseException:
                with self._condition:
                    self._loading.discard(registry_key)
                    self._condition.notify_all()
                raise
            break

        model = None
        try:
            model = accelerator.run_step(
                load,
                phase="residency.load",
            )
            observed = (
                estimated
                if observe_bytes is None
                else int(
                    accelerator.run_step(
                        lambda: observe_bytes(model),
                        phase="residency.measure",
                    )
                )
            )
            if observed <= 0:
                raise ValueError(
                    "observed model bytes must be positive"
                )
            with self._condition:
                projected = self._resident_bytes_locked() + observed
                if projected > maximum_bytes:
                    self._overage_count += 1
                    self._last_pressure_action = {
                        "action": "observed_overage",
                        "estimated_bytes": estimated,
                        "observed_bytes": observed,
                        "projected_bytes": projected,
                        "budget_bytes": maximum_bytes,
                    }
                    raise RuntimeError(
                        "observed model residency exceeds reserved capacity"
                    )
                entry = _ModelEntry(
                    registry_key,
                    model,
                    estimated,
                    observed,
                    unload,
                    ttl,
                    partition,
                )
                self._entries[registry_key] = entry
                self._active_leases += 1
                self._load_count += 1
                return _ModelLease(self, entry)
        except BaseException:
            if model is not None and unload is not None:
                try:
                    accelerator.run_step(
                        lambda: unload(model),
                        phase="residency.rollback",
                    )
                except BaseException:
                    pass
            raise
        finally:
            with self._condition:
                self._loading.discard(registry_key)
                self._condition.notify_all()

    def release(self, key):
        with self._condition:
            entry = self._entries.get(key)
            if entry is None or entry.leases <= 0:
                return
            entry.leases -= 1
            entry.last_used = time.monotonic()
            self._active_leases -= 1
            self._condition.notify_all()

    def evict_idle(self, accelerator, *, force=False):
        with self._condition:
            entries = self._idle_candidates_locked(
                time.monotonic(),
                force,
            )
            for entry in entries:
                if self._entries.pop(entry.key, None) is entry:
                    self._evicting.add(entry.key)
                    self._eviction_count += 1
        self._unload_entries(accelerator, entries)
        return len(entries)

    def apply_pressure(
        self,
        accelerator,
        *,
        level,
        measure,
        synchronize,
        clear_cache,
    ):
        if level not in ("soft", "throttle", "shed", "critical"):
            raise ValueError("unknown accelerator pressure level")
        if level == "soft":
            return {
                "action": "evict_idle",
                "evicted": self.evict_idle(
                    accelerator,
                    force=True,
                ),
            }
        config = accelerator.configuration
        minimum_interval = (
            int(config["cache_clear_minimum_interval_ms"]) / 1000.0
        )
        now = time.monotonic()
        with self._condition:
            if self._active_leases != 0:
                return {
                    "action": "deferred_active_leases",
                    "active_leases": self._active_leases,
                }
            if self._loading or self._evicting:
                return {
                    "action": "deferred_residency_transition",
                    "loading": len(self._loading),
                    "evicting": len(self._evicting),
                }
            if self._cache_clear_in_flight:
                return {"action": "deferred_in_flight"}
            elapsed = now - self._last_cache_clear
            if elapsed < minimum_interval:
                return {
                    "action": "hysteresis",
                    "retry_after_seconds":
                        minimum_interval - elapsed,
                }
            self._cache_clear_in_flight = True

        started = time.monotonic_ns()
        try:
            evicted = self.evict_idle(accelerator, force=True)
            before = int(
                accelerator.run_step(
                    measure,
                    phase="pressure.measure_before",
                )
            )
            accelerator.run_step(
                synchronize,
                phase="pressure.synchronize",
            )
            accelerator.run_step(
                clear_cache,
                phase="pressure.clear_cache",
            )
            after = int(
                accelerator.run_step(
                    measure,
                    phase="pressure.measure_after",
                )
            )
            if before < 0 or after < 0:
                raise ValueError(
                    "accelerator memory measurements must be "
                    "non-negative"
                )
            action = {
                "action": "cache_clear",
                "level": level,
                "evicted": evicted,
                "before_bytes": before,
                "after_bytes": after,
                "recovered_bytes": max(0, before - after),
                "duration_ns": time.monotonic_ns() - started,
            }
            with self._condition:
                self._last_cache_clear = time.monotonic()
                self._last_pressure_action = dict(action)
            return action
        finally:
            with self._condition:
                self._cache_clear_in_flight = False
                self._condition.notify_all()

    @property
    def snapshot(self):
        with self._condition:
            return {
                "models": len(self._entries),
                "resident_bytes": self._resident_bytes_locked(),
                "active_leases": self._active_leases,
                "loading": len(self._loading),
                "evicting": len(self._evicting),
                "load_count": self._load_count,
                "eviction_count": self._eviction_count,
                "overage_count": self._overage_count,
                "last_pressure_action": (
                    None
                    if self._last_pressure_action is None
                    else dict(self._last_pressure_action)
                ),
            }


_MODEL_REGISTRY = _ModelRegistry()


class DuplexAccelerator:
    __slots__ = (
        "_session",
        "_configuration",
        "_phase_timings",
        "_first_output_ns",
        "_playback_ns",
    )

    def __init__(self, session):
        self._session = session
        self._configuration = dict(
            session.configuration.get("accelerator", {})
        )
        self._phase_timings = {}
        self._first_output_ns = None
        self._playback_ns = None

    @property
    def available(self):
        return self._configuration.get("kind") == "mlx"

    @property
    def configuration(self):
        return dict(self._configuration)

    @property
    def lane_thread_id(self):
        self._require_available()
        return int(
            _native.accelerator_snapshot(
                self._session._token
            )["lane_thread_id"]
        )

    def _require_available(self):
        if not self.available:
            raise AcceleratorUnavailableError(
                "this duplex session has no MLX accelerator lane"
            )

    def run_step(
        self,
        callable,
        *,
        phase="evaluate",
        estimated_cost=1,
    ):
        self._require_available()
        phase = str(phase)
        result = _native.accelerator_run(
            self._session._token,
            callable,
            phase,
            int(estimated_cost),
        )
        snapshot = _native.accelerator_snapshot(
            self._session._token
        )
        if (
            phase not in self._phase_timings
            and len(self._phase_timings)
                >= _MAXIMUM_PHASE_TIMINGS
        ):
            del self._phase_timings[
                next(iter(self._phase_timings))
            ]
        self._phase_timings[phase] = {
            "queue_wait_ns": int(snapshot["queue_wait_ns"]),
            "execution_ns": int(snapshot["execution_ns"]),
            "lane_thread_id": int(snapshot["lane_thread_id"]),
        }
        return result

    def warmup(
        self,
        *,
        representative_shapes,
        prepare,
        evaluate,
        synchronize,
    ):
        self._require_available()
        shapes = []
        for shape in representative_shapes:
            if len(shapes) >= _MAXIMUM_WARMUP_SHAPES:
                raise ValueError(
                    "warmup representative_shapes exceeds "
                    "the bounded helper limit"
                )
            shapes.append(shape)
        if not shapes:
            raise ValueError(
                "warmup requires representative_shapes"
            )
        started = time.monotonic_ns()
        _native.accelerator_begin_warmup(self._session._token)
        try:
            self.run_step(prepare, phase="warmup.prepare")
            for shape in shapes:
                self.run_step(
                    lambda shape=shape: evaluate(shape),
                    phase="warmup.evaluate",
                )
            self.run_step(
                synchronize,
                phase="warmup.synchronize",
            )
            elapsed = time.monotonic_ns() - started
            timeout_ns = (
                int(self._configuration["warmup_timeout_ms"])
                * 1_000_000
            )
            if elapsed > timeout_ns:
                raise TimeoutError(
                    "MLX representative warm-up exceeded its policy timeout"
                )
            _native.accelerator_finish_warmup(
                self._session._token,
                len(shapes),
            )
            return self.latency_snapshot
        except BaseException:
            _native.accelerator_abort_warmup(
                self._session._token
            )
            raise

    def model_lease(
        self,
        *,
        key,
        estimated_bytes,
        load,
        unload=None,
        ttl_seconds=None,
        observe_bytes=None,
        partition=None,
    ):
        self._require_available()
        return _MODEL_REGISTRY.lease(
            self,
            key=key,
            estimated_bytes=estimated_bytes,
            load=load,
            unload=unload,
            ttl_seconds=ttl_seconds,
            observe_bytes=observe_bytes,
            partition=partition,
        )

    def evict_idle_models(self, *, force=False):
        self._require_available()
        return _MODEL_REGISTRY.evict_idle(
            self,
            force=bool(force),
        )

    def apply_pressure(
        self,
        level,
        *,
        measure,
        synchronize,
        clear_cache,
    ):
        self._require_available()
        _native.accelerator_begin_maintenance(
            self._session._token
        )
        try:
            return _MODEL_REGISTRY.apply_pressure(
                self,
                level=str(level),
                measure=measure,
                synchronize=synchronize,
                clear_cache=clear_cache,
            )
        finally:
            _native.accelerator_finish_maintenance(
                self._session._token
            )

    def state_window(
        self,
        *,
        maximum_items=None,
        maximum_bytes=None,
    ):
        self._require_available()
        configured_items = int(
            self._configuration["maximum_state_items"]
        )
        configured_bytes = int(
            self._configuration["maximum_state_bytes"]
        )
        requested_items = (
            configured_items
            if maximum_items is None
            else int(maximum_items)
        )
        requested_bytes = (
            configured_bytes
            if maximum_bytes is None
            else int(maximum_bytes)
        )
        if (
            requested_items <= 0
            or requested_items > configured_items
            or requested_bytes <= 0
            or requested_bytes > configured_bytes
        ):
            raise ValueError(
                "state window bounds must be positive and no larger "
                "than the negotiated accelerator policy"
            )
        return BoundedStateWindow(
            requested_items,
            requested_bytes,
        )

    def mark_first_output(self):
        self._first_output_ns = time.monotonic_ns()

    def mark_playback_consumed(self):
        self._playback_ns = time.monotonic_ns()

    @property
    def latency_snapshot(self):
        native = (
            _native.accelerator_snapshot(self._session._token)
            if self.available
            else {}
        )
        return {
            "phases": dict(self._phase_timings),
            "first_output_ns": self._first_output_ns,
            "playback_consumed_ns": self._playback_ns,
            "queue_depth": int(native.get("queue_depth", 0)),
            "executing": bool(native.get("executing", False)),
            "phase": str(native.get("phase", "")),
            "active_sessions": int(
                native.get("active_sessions", 0)
            ),
            "completed_steps": int(
                native.get("completed_steps", 0)
            ),
            "rejected_steps": int(
                native.get("rejected_steps", 0)
            ),
        }

    @property
    def residency_snapshot(self):
        return dict(_MODEL_REGISTRY.snapshot)


class InputFrame:
    __slots__ = (
        "sequence",
        "timestamp_ns",
        "format_id",
        "format",
        "format_metadata",
        "flags",
        "storage_route",
        "buffer",
    )

    def __init__(
        self,
        sequence,
        timestamp_ns,
        format_id,
        format,
        format_metadata,
        flags,
        storage_route,
        buffer,
    ):
        self.sequence = int(sequence)
        self.timestamp_ns = int(timestamp_ns)
        self.format_id = int(format_id)
        self.format = format
        self.format_metadata = dict(format_metadata)
        self.flags = int(flags)
        self.storage_route = str(storage_route)
        self.buffer = buffer

    @property
    def byte_count(self):
        view = memoryview(self.buffer)
        try:
            return view.nbytes
        finally:
            view.release()


class InputFinished:
    __slots__ = ("final_sequence",)

    def __init__(self, final_sequence):
        self.final_sequence = int(final_sequence)


class InputMessageAborted:
    __slots__ = ("message_id", "reason_code")

    def __init__(self, message_id, reason_code):
        self.message_id = str(message_id)
        self.reason_code = int(reason_code)


class InputMessageChunk:
    __slots__ = (
        "sequence",
        "timestamp_ns",
        "message_id",
        "total_bytes",
        "byte_offset",
        "chunk_index",
        "chunk_count",
        "format_id",
        "format",
        "format_metadata",
        "flags",
        "storage_route",
        "buffer",
    )

    def __init__(
        self,
        sequence,
        timestamp_ns,
        message_id,
        total_bytes,
        byte_offset,
        chunk_index,
        chunk_count,
        format_id,
        format,
        format_metadata,
        flags,
        storage_route,
        buffer,
    ):
        self.sequence = int(sequence)
        self.timestamp_ns = int(timestamp_ns)
        self.message_id = str(message_id)
        self.total_bytes = int(total_bytes)
        self.byte_offset = int(byte_offset)
        self.chunk_index = int(chunk_index)
        self.chunk_count = (
            None if chunk_count is None else int(chunk_count)
        )
        self.format_id = int(format_id)
        self.format = str(format)
        self.format_metadata = dict(format_metadata)
        self.flags = int(flags)
        self.storage_route = str(storage_route)
        self.buffer = buffer

    @property
    def byte_count(self):
        view = memoryview(self.buffer)
        try:
            return view.nbytes
        finally:
            view.release()


class InputMessage:
    __slots__ = (
        "_session",
        "_first",
        "_consumed",
        "_id",
        "_total_bytes",
        "_timestamp_ns",
        "_format",
        "_format_metadata",
        "_flags",
        "_storage_route",
    )

    def __init__(self, session, first):
        self._session = session
        self._first = first
        self._consumed = False
        self._id = first.message_id
        self._total_bytes = first.total_bytes
        self._timestamp_ns = first.timestamp_ns
        self._format = first.format
        self._format_metadata = dict(first.format_metadata)
        self._flags = first.flags
        self._storage_route = first.storage_route

    @property
    def id(self):
        return self._id

    @property
    def total_bytes(self):
        return self._total_bytes

    @property
    def timestamp_ns(self):
        return self._timestamp_ns

    @property
    def format(self):
        return self._format

    @property
    def format_metadata(self):
        return dict(self._format_metadata)

    @property
    def flags(self):
        return self._flags

    @property
    def storage_route(self):
        return self._storage_route

    def chunks(self):
        if self._consumed:
            raise RuntimeError("logical message chunks are single-consumer")
        self._consumed = True
        chunk = self._first
        self._first = None
        expected_offset = 0
        expected_index = 0
        while True:
            if (
                chunk.message_id != self.id
                or chunk.byte_offset != expected_offset
                or chunk.chunk_index != expected_index
                or chunk.total_bytes != self.total_bytes
            ):
                raise RuntimeError("logical message chunk order changed")
            yield chunk
            expected_offset += chunk.byte_count
            expected_index += 1
            if expected_offset == self.total_bytes:
                return
            # A one-credit stream cannot deliver the next chunk until
            # the previous leased exporter is released. Do not retain
            # it in this generator while blocking for its successor.
            chunk = None
            chunk = self._session._receive_message_chunk(self.id)

    def read(self, *, max_bytes):
        maximum = int(max_bytes)
        if maximum < 0 or self.total_bytes > maximum:
            raise ValueError("logical message exceeds caller reassembly bound")
        return b"".join(bytes(chunk.buffer) for chunk in self.chunks())


class ApplicationControl:
    __slots__ = (
        "sequence",
        "kind",
        "payload",
        "acknowledged_output_through",
    )

    def __init__(
        self,
        sequence,
        kind,
        payload,
        acknowledged_output_through,
    ):
        self.sequence = int(sequence)
        self.kind = str(kind)
        self.payload = payload
        self.acknowledged_output_through = acknowledged_output_through


class Interrupted:
    __slots__ = (
        "sequence",
        "id",
        "reason",
        "consumed_output_through",
        "generation",
    )

    def __init__(
        self,
        sequence,
        interruption_id,
        reason,
        consumed_output_through,
        generation,
    ):
        self.sequence = int(sequence)
        self.id = str(interruption_id)
        self.reason = str(reason)
        self.consumed_output_through = consumed_output_through
        self.generation = int(generation)


class Cancelled:
    __slots__ = ("reason",)

    def __init__(self, reason):
        self.reason = str(reason)


def _decode_event(raw):
    kind = raw["kind"]
    if kind == "input":
        return InputFrame(
            raw["sequence"],
            raw["timestamp_ns"],
            raw["format_id"],
            raw["format"],
            raw.get("format_metadata", {}),
            raw.get("flags", 0),
            raw.get("storage_route", "inline"),
            raw["buffer"],
        )
    if kind == "input_finished":
        return InputFinished(raw["final_sequence"])
    if kind == "message_chunk":
        return InputMessageChunk(
            raw["sequence"],
            raw["timestamp_ns"],
            raw["message_id"],
            raw["total_bytes"],
            raw["byte_offset"],
            raw["chunk_index"],
            raw["chunk_count"],
            raw["format_id"],
            raw["format"],
            raw["format_metadata"],
            raw["flags"],
            raw.get("storage_route", "inline"),
            raw["buffer"],
        )
    if kind == "message_aborted":
        return InputMessageAborted(
            raw["message_id"],
            raw["reason_code"],
        )
    if kind == "application":
        return ApplicationControl(
            raw["sequence"],
            raw["control_kind"],
            raw["payload"],
            raw["acknowledged_output_through"],
        )
    if kind == "interrupted":
        return Interrupted(
            raw["sequence"],
            raw["id"],
            raw["reason"],
            raw["consumed_output_through"],
            raw["generation"],
        )
    if kind == "cancelled":
        return Cancelled(raw["reason"])
    raise RuntimeError(f"unknown native duplex event kind: {kind!r}")


class DuplexOutput:
    __slots__ = ("_session",)

    def __init__(self, session):
        self._session = session

    def send(
        self,
        buffer,
        *,
        format=None,
        timestamp_ns=None,
        processed_input_through=None,
        flags=0,
    ):
        result = _native.send(
            self._session._token,
            buffer,
            format,
            timestamp_ns,
            processed_input_through,
            int(flags),
            True,
        )
        if result.startswith("cancelled:"):
            raise DuplexCancelledError(result.split(":", 1)[1])
        if result != "sent":
            raise RuntimeError(f"unexpected blocking send result: {result}")

    def try_send(
        self,
        buffer,
        *,
        format=None,
        timestamp_ns=None,
        processed_input_through=None,
        flags=0,
    ):
        result = _native.send(
            self._session._token,
            buffer,
            format,
            timestamp_ns,
            processed_input_through,
            int(flags),
            False,
        )
        if result.startswith("cancelled:"):
            raise DuplexCancelledError(result.split(":", 1)[1])
        if result == "sent":
            return SendDisposition.SENT
        if result == "would_block":
            return SendDisposition.WOULD_BLOCK
        raise RuntimeError(f"unexpected try_send result: {result}")

    def record_discontinuity(
        self,
        frames,
        *,
        bytes=0,
        duration_ns=0,
        reason=0,
    ):
        _native.record_discontinuity(
            self._session._token,
            int(frames),
            int(bytes),
            int(duration_ns),
            reason,
        )

    def finish(self):
        _native.finish_output(self._session._token)


class DuplexSession:
    __slots__ = (
        "_token",
        "_configuration",
        "_pending_events",
        "output",
        "accelerator",
    )

    def __init__(self, token):
        self._token = int(token)
        self._configuration = _native.configuration(self._token)
        self._pending_events = collections.deque()
        self.output = DuplexOutput(self)
        self.accelerator = DuplexAccelerator(self)

    @property
    def configuration(self):
        return self._configuration

    @property
    def formats(self):
        return tuple(self._configuration["formats"])

    @property
    def handler_thread_id(self):
        return int(_native.handler_thread_id(self._token))

    def ready(self, metadata=None):
        _native.ready(self._token, metadata)

    def receive(self, timeout=None):
        if timeout is not None:
            timeout = float(timeout)
            if not math.isfinite(timeout) or timeout < 0:
                raise ValueError(
                    "receive timeout must be finite and non-negative"
                )
        if self._pending_events:
            return self._pending_events.popleft()
        return _decode_event(_native.receive(self._token, timeout))

    def _receive_message_chunk(self, message_id):
        for index, event in enumerate(self._pending_events):
            if (
                isinstance(event, InputMessageChunk)
                and event.message_id == message_id
            ):
                del self._pending_events[index]
                return event
            if (
                isinstance(event, InputMessageAborted)
                and event.message_id == message_id
            ):
                del self._pending_events[index]
                raise DuplexMessageAbortedError(
                    event.message_id,
                    event.reason_code,
                )
        while True:
            event = _decode_event(_native.receive(self._token, None))
            if (
                isinstance(event, InputMessageChunk)
                and event.message_id == message_id
            ):
                return event
            if (
                isinstance(event, InputMessageAborted)
                and event.message_id == message_id
            ):
                raise DuplexMessageAbortedError(
                    event.message_id,
                    event.reason_code,
                )
            if isinstance(event, InputFinished):
                raise RuntimeError(
                    "input ended before logical message completed"
                )
            self._pending_events.append(event)

    def receive_message(self, timeout=None):
        if timeout is not None:
            timeout = float(timeout)
            if not math.isfinite(timeout) or timeout < 0:
                raise ValueError(
                    "receive timeout must be finite and non-negative"
                )
        for index, event in enumerate(self._pending_events):
            if isinstance(event, InputMessageChunk):
                del self._pending_events[index]
                return InputMessage(self, event)
        for event in self._pending_events:
            if isinstance(event, InputFinished):
                raise RuntimeError(
                    "input ended before a logical message arrived"
                )
            if isinstance(event, Cancelled):
                raise DuplexCancelledError(event.reason)
        deadline = (
            None if timeout is None else time.monotonic() + timeout
        )
        while True:
            remaining = (
                None
                if deadline is None
                else max(0.0, deadline - time.monotonic())
            )
            event = _decode_event(
                _native.receive(self._token, remaining)
            )
            if isinstance(event, InputMessageChunk):
                return InputMessage(self, event)
            self._pending_events.append(event)
            if isinstance(event, InputFinished):
                raise RuntimeError(
                    "input ended before a logical message arrived"
                )
            if isinstance(event, Cancelled):
                raise DuplexCancelledError(event.reason)

    def iter_input(self, *, control_policy="yield"):
        if control_policy not in ("yield", "ignore", "raise"):
            raise ValueError(
                "control_policy must be 'yield', 'ignore', or 'raise'"
            )
        while True:
            event = self.receive()
            if isinstance(event, InputFinished):
                return
            if isinstance(event, Cancelled):
                raise DuplexCancelledError(event.reason)
            if isinstance(event, InputFrame) or control_policy == "yield":
                yield event
            elif control_policy == "raise":
                raise RuntimeError(
                    "iter_input received a control event; use "
                    "control_policy='yield' or receive()"
                )

    @property
    def cancelled(self):
        return _native.cancel_reason(self._token) is not None

    def check_cancelled(self):
        reason = _native.cancel_reason(self._token)
        if reason is not None:
            raise DuplexCancelledError(reason)

    @property
    def interruption_requested(self):
        return int(_native.interruption_generation(self._token))

    def latest_interruption(self):
        raw = _native.latest_interruption(self._token)
        return None if raw is None else _decode_event(raw)

    def send_event(
        self,
        kind,
        payload=None,
        *,
        produced_through=None,
        processed_input_through=None,
    ):
        kind = str(kind)
        if (
            not kind
            or len(kind.encode("utf-8")) > 256
            or kind.startswith("swiftpython.")
            or kind.startswith("controlApplied.")
            or kind.startswith("controlRejected.")
            or kind.startswith("interruptionCompleted.")
        ):
            raise ValueError(
                "application event kind is empty, reserved, or too large"
            )
        _native.send_event(
            self._token,
            kind,
            payload,
            produced_through,
            processed_input_through,
        )

    def interruption_completed(self, id, disposition):
        if isinstance(disposition, InterruptionDisposition):
            disposition = disposition.value
        else:
            disposition = str(disposition)
        allowed = {
            value.value for value in InterruptionDisposition
        }
        if disposition not in allowed:
            raise ValueError(
                "interruption disposition must describe actual "
                "state truncation support"
            )
        _native.interruption_completed(
            self._token,
            str(id),
            disposition,
        )


def unavailable_capability_declaration(protocol_version):
    """Honest v6 declaration used until a media backend is enabled."""
    return {
        "protocolVersion": protocol_version,
        "features": [],
        "transports": [],
        "payloadRoutes": [],
        "helperSchemas": [],
        "limits": {
            "maxControlPayloadBytes": 1024 * 1024,
            "maxMediaFrameBytes": 0,
            "maxActiveDuplexSessions": 0,
            "maxIngressCreditBytes": 0,
            "maxEgressCreditBytes": 0,
            "maxIngressCreditFrames": 0,
            "maxEgressCreditFrames": 0,
            "helperSchemaVersion": DUPLEX_HELPER_SCHEMA_VERSION,
            "maxLogicalMessageBytes": 0,
            "preferredMessageChunkBytes": 0,
            "maxOutstandingMessages": 0,
        },
    }


def capability_declaration(protocol_version, transport):
    """Declare exactly the one media transport this guest can open."""
    if transport not in ("duplex.uds.v1", "duplex.vsock.v1"):
        raise ValueError(f"unsupported guest duplex transport: {transport!r}")
    max_frame_bytes = (
        DUPLEX_MAXIMUM_VSOCK_MEDIA_FRAME_BYTES
        if transport == "duplex.vsock.v1"
        else DUPLEX_MAXIMUM_MEDIA_FRAME_BYTES
    )
    return {
        "protocolVersion": protocol_version,
        "features": [
            "duplex.sessions.v1",
            "duplex.messages.v1",
        ],
        "transports": [{
            "kind": transport,
            "mediaProtocolVersion": DUPLEX_MEDIA_PROTOCOL_VERSION,
            "supportedMediaProtocolVersions": [
                DUPLEX_MEDIA_PROTOCOL_VERSION,
            ],
            "maxFrameBytes": max_frame_bytes,
            "preferredChunkBytes":
                DUPLEX_PREFERRED_MESSAGE_CHUNK_BYTES,
            "authenticationModes": ["hmac-sha256"],
            "checksumModes": ["none"],
        }],
        "payloadRoutes": [],
        "helperSchemas": [{
            "feature": "duplex.messages.v1",
            "version": 1,
        }],
        "limits": {
            "maxControlPayloadBytes":
                DUPLEX_MAXIMUM_CONTROL_PAYLOAD_BYTES,
            "maxMediaFrameBytes": max_frame_bytes,
            "maxActiveDuplexSessions":
                DUPLEX_MAXIMUM_ACTIVE_SESSIONS,
            "maxIngressCreditBytes":
                DUPLEX_MAXIMUM_INGRESS_CREDIT_BYTES,
            "maxEgressCreditBytes":
                DUPLEX_MAXIMUM_EGRESS_CREDIT_BYTES,
            "maxIngressCreditFrames":
                DUPLEX_MAXIMUM_CREDIT_FRAMES,
            "maxEgressCreditFrames":
                DUPLEX_MAXIMUM_CREDIT_FRAMES,
            "helperSchemaVersion": DUPLEX_HELPER_SCHEMA_VERSION,
            "maxLogicalMessageBytes":
                DUPLEX_MAXIMUM_LOGICAL_MESSAGE_BYTES,
            "preferredMessageChunkBytes":
                DUPLEX_PREFERRED_MESSAGE_CHUNK_BYTES,
            "maxOutstandingMessages":
                DUPLEX_MAXIMUM_OUTSTANDING_MESSAGES,
        },
    }
