// swift-tools-version: 6.0
import PackageDescription
import Foundation

// SwiftPython Studio — a flagship demo app built on the commercial
// SwiftPythonRuntime xcframework. It showcases the canonical V2 `pool.<module>`
// surface (vendored as `SwiftPythonKit`) by racing several scikit-learn models
// across Python worker processes, live, from Swift.

private func parseSemVer(_ raw: String) -> Version? {
    let core = raw.split(separator: "-", maxSplits: 1).first.map(String.init) ?? raw
    let parts = core.split(separator: ".", omittingEmptySubsequences: false)
    guard parts.count == 3, let a = Int(parts[0]), let b = Int(parts[1]), let c = Int(parts[2]) else { return nil }
    return Version(a, b, c)
}

private let swiftPythonPackageName = "swiftpython-commercial"

private struct SwiftPythonDependencyConfig {
    let dependency: Package.Dependency
    let packageName: String
}

private func packageNameFromDependencyURL(_ rawURL: String) -> String {
    var trimmed = rawURL.trimmingCharacters(in: .whitespacesAndNewlines)
    while trimmed.hasSuffix("/") { trimmed.removeLast() }
    let base = (trimmed as NSString).lastPathComponent
    return base.hasSuffix(".git") ? String(base.dropLast(4)) : base
}

private func swiftPythonConfig() -> SwiftPythonDependencyConfig {
    let env = ProcessInfo.processInfo.environment
    if let url = env["SWIFTPYTHON_COMMERCIAL_PACKAGE_URL"]?.trimmingCharacters(in: .whitespacesAndNewlines),
       !url.isEmpty,
       let versionRaw = env["SWIFTPYTHON_COMMERCIAL_PACKAGE_VERSION"]?.trimmingCharacters(in: .whitespacesAndNewlines),
       !versionRaw.isEmpty {
        guard let version = parseSemVer(versionRaw) else {
            fatalError("SWIFTPYTHON_COMMERCIAL_PACKAGE_VERSION must be MAJOR.MINOR.PATCH")
        }
        return SwiftPythonDependencyConfig(
            dependency: .package(url: url, exact: version),
            packageName: packageNameFromDependencyURL(url)
        )
    }
    return SwiftPythonDependencyConfig(
        dependency: .package(name: swiftPythonPackageName, path: "../.."),
        packageName: swiftPythonPackageName
    )
}

private func pythonLibraryDirectory() -> String {
    let env = ProcessInfo.processInfo.environment
    if let explicit = env["SWIFTPYTHON_PYTHON_LIB_DIR"]?.trimmingCharacters(in: .whitespacesAndNewlines), !explicit.isEmpty {
        return explicit
    }
    if let home = (env["PYTHON_HOME"] ?? env["PYTHONHOME"])?.trimmingCharacters(in: .whitespacesAndNewlines), !home.isEmpty {
        let frameworkLib = "\(home)/Frameworks/Python.framework/Versions/3.13/lib"
        return FileManager.default.fileExists(atPath: frameworkLib) ? frameworkLib : "\(home)/lib"
    }
    let candidates = [
        "/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib",
        "/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib",
        "/opt/homebrew/opt/python@3.13/lib",
        "/usr/local/opt/python@3.13/lib",
    ]
    return candidates.first { FileManager.default.fileExists(atPath: $0) } ?? candidates[0]
}

private let pythonLinkerSettings: [LinkerSetting] = [
    .unsafeFlags(["-L\(pythonLibraryDirectory())", "-lpython3.13"])
]

private let config = swiftPythonConfig()

let package = Package(
    name: "Studio",
    platforms: [.macOS(.v15)],
    dependencies: [config.dependency],
    targets: [
        // Vendored canonical V2 pool bindings (generated by `swift-python-gen --surface pool`).
        .target(
            name: "SwiftPythonKit",
            dependencies: [.product(name: "SwiftPythonRuntime", package: config.packageName)]
        ),
        .executableTarget(
            name: "Studio",
            dependencies: [
                "SwiftPythonKit",
                .product(name: "SwiftPythonRuntime", package: config.packageName),
            ],
            path: "Sources/Studio",
            linkerSettings: pythonLinkerSettings
        ),
        .executableTarget(
            name: "studio-cli",
            dependencies: [
                "SwiftPythonKit",
                .product(name: "SwiftPythonRuntime", package: config.packageName),
            ],
            path: "Sources/studio-cli",
            linkerSettings: pythonLinkerSettings
        ),
    ]
)
